check_task:
    name: "Check"
    windows_container:
        image: cirrusci/windowsservercore:2019
    env:
        PATH: "${PATH};C:\\ProgramData\\chocolatey\\bin"
        CIRRUS_SHELL: powershell
        CIRRUS_CLONE_DEPTH: 1
        # Fake version, we are only testing the installer functions, so version doesn't matter
        WIN_INST_VER: 9.9.9
    main_script: | 
        Write-Output "Work:"
        Write-Output $Env:CIRRUS_WORKING_DIR
        Write-Output "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
        Write-Output "Location:"
        Get-Location
        Write-Output "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
        Write-Output "ENV:"
        dir env:
