aws_credentials: ENCRYPTED[21c833dbc0f664e4dc54072e1ec520bdb5c6b5afbd1c2cbba1dd6c08e4bd3225c654c4d6a9d3e1f0117716529f7fac27]

check_task:
    name: "Check"
    ec2_instance: &standard_build_ec2_aarch64
        image: "win-server-wsl*"
        type: t3.large
        region: us-east-1
        platform: windows
    env:
        PATH: "${PATH};C:\\ProgramData\\chocolatey\\bin"
        CIRRUS_SHELL: powershell
        CIRRUS_CLONE_DEPTH: 1
        # Fake version, we are only testing the installer functions, so version doesn't matter
        WIN_INST_VER: 9.9.9
        CIRRUS_WORKING_DIR: "${LOCALAPPDATA}\\Temp\\new-cirrus-ci-build"
    main_script: | 
        Write-Output "Works!"
        $x = wsl --status
        Write-Output $x
